name: demand-allocator
channels:
  - conda-forge
dependencies:
  - python 3.10
  - geopandas
  - geopy
  - pandas
  - fastapi
  - unidecode
  - uvicorn
  - libpysal
  - python-multipart
  - osmnx
  - pandana
  - numpy
  - matplotlib
  - reportlab
