name: demand-allocator
channels:
  - conda-forge
dependencies:
  - python=3.10.18
  - geopandas=1.1.0
  - geopy=2.4.1
  - pandas=2.3.0
  - fastapi=0.115.13
  - unidecode=1.3.8
  - uvicorn=0.34.3
  - python-multipart=0.0.20
  - osmnx=2.0.4
  - pandana=0.7
  - numpy=2.2.6
  - matplotlib=3.10.3
  - reportlab=4.4.1
